name = "SMeshSmokeValidation"
uuid = "03aa94ec-4857-4b70-b643-f5d81c7dd350"
authors = ["Daniel Neamati <danineamati@gmail.com>", "Evan Twarog <etwarog@stanford.edu>"]
version = "1.0.0-DEV"

[deps]
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
LazySets = "3.1.0"
LinearAlgebra = "1.11.0"
Plots = "1.40.9"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
